CREATE table employee(
  SSN VARCHAR2(5) primary KEY not null,
  fName VARCHAR2(30),
  lName VARCHAR2(30),
  Address VARCHAR2(30),
  Sex VARCHAR2(10),
  Salary NUMBER(10,2) CHECK (Salary >0 ),
  upperSSN VARCHAR2(50),
  Dno INTEGER
);
insert into  employee values ('E101', 'John', 'Doe', '123 Main St', 'M',50000,'U101',1);
create table department(
  Dno INTEGER PRIMARY KEY NOT NULL,
  DName VARCHAR2(30),
  MgrSSN VARCHAR2(5),
  MgrStartDate DATE
);
INSERT into DEPARTMENT VALUES(1,'IOT','M101','11/10/21');
INSERT INTO DEPARTMENT VALUES(2,'Management','M102','18/08/20');
INSERT INTO DEPARTMENT VALUES(3,'Business','M102','11/10/21');
INSERT INTO DEPARTMENT VALUES(4,'Software','M102','11/10/21');
INSERT INTO DEPARTMENT VALUES(5,'Accounts','M102','11/10/21');

CREATE TABLE DLOCATION (
    DNo INT,
    DLoc VARCHAR(100),
    PRIMARY KEY (DNo, DLoc),
    FOREIGN KEY (DNo) REFERENCES DEPARTMENT(DNo) ON DELETE CASCADE
);

CREATE TABLE PROJECT (
    PNo INT PRIMARY KEY,
    PName VARCHAR(50) NOT NULL,
    PLocation VARCHAR(100),
    DNo INT,
    FOREIGN KEY (DNo) REFERENCES DEPARTMENT(DNo) ON DELETE SET NULL
);
CREATE TABLE WORKS_ON (
    SSN VARCHAR2(9),
    PNo INT,
    Hours DECIMAL(4, 1) CHECK (Hours > 0),
    PRIMARY KEY (SSN, PNo),
    FOREIGN KEY (SSN) REFERENCES EMPLOYEE(SSN) ON DELETE CASCADE,
    FOREIGN KEY (PNo) REFERENCES PROJECT(PNo) ON DELETE CASCADE
);